### ISSUE TITLE
 is there any communication group

### ISSUE THREAD

**Issue by zhouyongxiu** [iarai/Landslide4Sense-2022#1]
I find some label incorrect，is there any communication group to join in?

**Comment by YonghaoXu** [comment]
Hi, there is a competition forum where you can post your questions or issues:
https://www.iarai.ac.at/landslide4sense/forums/

The annotation of the Landslide4Sense dataset is manually collected by landslide experts referring to the corresponding very high-resolution imagery. Thus, there may exist inaccuracy in particular regions and we treat them as potential noises in the competition.
