### ISSUE TITLE
Could you please provide the mask for the validation dataset?

### ISSUE THREAD

**Issue by dwXzd** [iarai/Landslide4Sense-2022#10]
Hello! Thanks for your job to provide such a dataset for landslide detection! Recently I have been working on this dataset to do the semantic segmentation task. I use all the traing data to train the model because the valid training data (including landslide) is not enough compare to some traditional dataset like COCO or Pascal VOC. So could you please provide the mask for the validation dataset to help me evaluate the model profermance? Thank you.

**Comment by YonghaoXu** [comment]
Hi, the complete dataset including the labels is now available at: https://zenodo.org/records/10463239

**Comment by dwXzd** [comment]
Thank you！
