### ISSUE TITLE
Competition forum does not work

### ISSUE THREAD

**Issue by adamstj** [iarai/Landslide4Sense-2022#2]
Hi, the competition forum keeps redirecting and returns:
"www.iarai.ac.at redirected you too many times."

I dont know if this is only an issue for me? (I tried clearing cookies as well).

I have a question regarding the normalization of values in the 14 bands. How has it been performed? I would like to compute band combinations, so I need to understand how the values have been converted in the first place, they are not normalized to be between 0-1?

**Comment by YonghaoXu** [comment]
Hi, to access the forum, you need to first log in to the IARAI website.

The 14 bands are simply divided by a mean vector to implement the normalization:
`
img_mean = [1111.81236406,  824.63171476,  663.41636217,  445.17289745,  645.8582926,
 			1547.73508126, 1960.44401001, 1941.32229668,  674.07572865,    9.04787384,
 			1113.98338755,  519.90397929,   20.29228266,  772.83144788]
`

**Comment by adamstj** [comment]
Thank you!
